# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

campsites = Campsite.create([
                              {
                                name: 'Desoto State Park',
                                state: 'AL',
                                address: '7104 Desoto Pkwy NE, Fort Payne, AL 35967',
                                phone_number: '256-845-5075',
                                website: 'https://www.alapark.com/parks/desoto-state-park',
                                description: 'Sitting atop Lookout Mountain, Desoto State Park offers campers the chance to embrace nature in Northeast Alabama. Waterfalls and wildflowers make for a scenic camping experience and activities range from hiking to swimming in the park’s seasonal pool. There are 94 full hook-up sites, as well as cabins, cottages, challets, and even 2 backpacking sites for those who want to get away from the more developed side of things.',
                                full_hookups: true,
                                partial_hookups: true,
                                fishing: true,
                                showers: true,
                                bathrooms: true,
                                map_img_url: '',
                                site_img_url: '',
                                season: 'year round'
                              }
                              # {
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # }

                              # {
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # },{
                              #   name: ,
                              #   state: ,
                              #   address: ,
                              #   phone_number: ,
                              #   website: ,
                              #   description: ,
                              #   full_hookups: ,
                              #   partial_hookups: ,
                              #   fishing: ,
                              #   showers: ,
                              #   bathrooms: ,
                              #   map_img_url: ,
                              #   site_img_url: ,
                              #   season: ,
                              # }
                            ])
